### ISSUE TITLE
Typescript supporting

### ISSUE THREAD

**Issue by sleagon** [jonschlinkert/time-stamp#12]
Need ts supporting. Fixed in [PR#11](https://github.com/jonschlinkert/time-stamp/pull/11)

**Comment by mario-huang** [comment]
It seem that the index.d.ts has some problem.
When I wirte
```
import timestamp from 'time-stamp'
timestamp('YYYY.MM.DD.HH.mm.ss')
```
Run tsc is fine. But the js file goes wrong.
TypeError: time_stamp_1.default is not a function

**Comment by doowb** [comment]
@myeveryheart try:

```js
import * as timestamp from 'time-stamp';
```

If there's a way to specify in the `index.d.ts` file the syntax that you'd like to use, please submit a PR with the change.
