### ISSUE TITLE
Use 'YYYY-MM-DD' as default pattern

### ISSUE THREAD

**Issue by leesei** [jonschlinkert/time-stamp#3]
It is the [ISO 8601](https://www.wikiwand.com/en/ISO_8601) date format.

![](http://imgs.xkcd.com/comics/iso_8601.png)

**Comment by jonschlinkert** [comment]
if someone wants to do a pr for this that would be great, or I can do this as soon as I have a change. I would have done it in the last release but it slipped my mind...
