### ISSUE TITLE
Question: What is the difference between node-dateformat package and time-stamp package

### ISSUE THREAD

**Issue by bboydflo** [jonschlinkert/time-stamp#9]
Hi, and thanks for the many packages you maintain. I wanted to use node-dateformat package and then found time-stamp package both seem to do the same thing. what is the difference?

**Comment by doowb** [comment]
I think it depends on how you want to use it. `time-stamp` focuses on a few supported patterns mainly to make it fast to output a timestamp like `[11:34:02]`. `dateformat` does a lot more parsing to be flexible in how you output a date string.

Both are downloaded close to the same amount:

| package | downloads |
|---|---|
|`timestamp`| ![NPM monthly downloads](https://img.shields.io/npm/dm/time-stamp.svg?style=flat) |
|`dateformat`| ![NPM monthly downloads](https://img.shields.io/npm/dm/dateformat.svg?style=flat) |

Hope this helps. I'm going to close the issue, but if you find a bug feel free to open a new issue.

**Comment by jonschlinkert** [comment]
This library does time-stamps, that's all. dateformat does a lot more. Both readmes have more detail. Fwiw I co-maintain node-dateformat too.
